### ISSUE TITLE
argparse improvements

### ISSUE THREAD

**Issue by gkthiruvathukal** [jweezy24/Moonshine#3]
- Make all argparse options lowercase.
- Consider using `default=` to set default values for the various options so users can just run the script with meaningful defaults.
-

**Comment by gkthiruvathukal** [comment]
This would allow you to replace:
```
  python3 scripts/prepare_python_experiments.py --data_path '' --         NIST_path '' --Moonshine_path ''
```

with 
```
  $(PYTHON) scripts/prepare_python_experiments.py
```

Only if a user needed to do something different would they use the `--data_path`, etc. options.

**Comment by jweezy24** [comment]
Fixed issue 3
